### ISSUE TITLE
Allow passing query parameters

### ISSUE THREAD

**Issue by pimterry** [mohsen1/service-worker-loader#101]
I need to pass some dynamic query parameters to my service worker, which vary at runtime. This is pretty easy in theory (just include them in the URL like normal), but isn't possible with this loader because it expects the entire URL at build time.

Would you be interesting in supporting this? I'd be happy to put a PR together. I'd suggest an extra param on the default export function, for params to append to `scriptUrl`.

**Comment by dangreen** [comment]
Hi! Can you tell more about your use case?

сб, 18 янв. 2020 г. в 03:14, Tim Perry <notifications@github.com>:

**Comment by pimterry** [comment]
Sure. When my page first opens, it's given some config params in the URL. These are independent of the page itself, and I need them to communicate with an external service. The service worker also needs these params at startup, immediately, _before_ it installs.

There are ways to pass this via postMessage etc, but it gets very messy very quickly. Instead, I'd like to simply register `/service-worker.js?param=abc` as my service worker. That's perfectly possible & valid, very easy, and it works fine if I do it manually, but it's not possible with this library right now.

**Comment by dangreen** [comment]
Why not local storage or cookies?

пн, 20 янв. 2020 г. в 17:02, Tim Perry <notifications@github.com>:

**Comment by pimterry** [comment]
Service workers can't read either localstorage or cookies.

**Comment by dangreen** [comment]
@pimterry 
```js
import {
    scriptUrl
} from 'service-worker-loader!./sw';

navigator.serviceWorker.register(`${scriptUrl}?param=abc`).then((registration) => {
    console.log(registration);
});
```

**Comment by pimterry** [comment]
That works, that's pretty much how I've been testing it until now. That skips the error handling etc from the standard logic too though: https://github.com/mohsen1/service-worker-loader/blob/master/src/serviceWorker.js.

It would be nicer if this was built-in, instead of having to reimplement all the runtime code from this lib to do this. This might also be useful to others too - query params are the easiest & almost the only option available if you want to provide any initial runtime config to a service worker.

If you're not happy with including that, that's OK, but I'd be happy to put the PR together if you might be interested.

**Comment by dangreen** [comment]
@pimterry 

https://github.com/mohsen1/service-worker-loader#registerserviceworkermapscripturl-scripturl-string--string-options-registrationoptions-promiseserviceworkerregistration

**Comment by pimterry** [comment]
Thanks @dangreen! This is great, I've updated and started using it, seems to work perfectly :+1:. Thanks for your help.
