### ISSUE TITLE
Error on IE11

### ISSUE THREAD

**Issue by ts1** [mohsen1/service-worker-loader#11]
On IE11 it throws syntax error because IE does not support `class` syntax.
Consequently the whole webpack'ed bundle is not usable on IE, I have to use `await import(...)`, which generates an extraneous small chunk.
What I really want is the `ServiceWorkerNoSupportError`, because it is there for that purpose.

**Comment by dangreen** [comment]
@ts1 fix will be published in https://github.com/mohsen1/service-worker-loader/releases/tag/v3.1.0

**Comment by ts1** [comment]
Tried v3.1.0 and it works great on IE.
Thanks a lot!

**Comment by dangreen** [comment]
@ts1 update was published on npm

**Comment by ts1** [comment]
@dangreen Thank you!
