### ISSUE TITLE
Public path is not respected

### ISSUE THREAD

**Issue by vincaslt** [mohsen1/service-worker-loader#143]
Public path set by webpack is not respected and `/` is used instead.

Seems like https://github.com/mohsen1/service-worker-loader/blob/master/src/index.js#L42 sets `/` as a default and https://github.com/mohsen1/service-worker-loader/blob/master/src/index.js#L84 can never use the webpack setting.

**Comment by vincaslt** [comment]
Could you make a new version on npm?

**Comment by dangreen** [comment]
Will publish during this week.

ср, 20 мая 2020 г. в 16:59, Vincas Stonys <notifications@github.com>:

**Comment by dangreen** [comment]
@vincaslt Thank you for issue and pr with fix!

[v4.0.2](https://github.com/mohsen1/service-worker-loader/releases/tag/v4.0.2)
